apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: premium-ssd 
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
reclaimPolicy: Retain # default value is Delete
provisioner: csi-driver.example-vendor.example
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
